export enum FeedType {
  RSS = 'RSS',
  VIRTUAL = 'VIRTUAL' // Generated by AI from a topic via Search Grounding
}

export interface Feed {
  id: string;
  url: string; // For VIRTUAL, this is the topic string
  title: string;
  type: FeedType;
  icon?: string;
  lastUpdated?: number;
}

export interface Article {
  id: string;
  feedId: string;
  title: string;
  link: string;
  pubDate: string;
  content: string;
  author?: string;
  thumbnail?: string;
  read: boolean;
  bookmarked: boolean;
  aiSummary?: string;
  tags?: string[];
}

export interface LoadingState {
  isLoading: boolean;
  message?: string;
}

export type ViewMode = 'dashboard' | 'feed' | 'article' | 'creator';

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
}

export interface AnalysisPreset {
  id: string;
  name: string;
  description?: string;
  prompt: string;
  icon?: string;
}
